### DISCUSSION TITLE
Support templating within the test name

### DISCUSSION THREAD

**Discussion by mmahut** [stepci/stepci#103] [Ideas]
Would it be possible to support templating within the testname as well?

```
name: Mirror testing
env:
  call: api/v0/blocks/latest
tests:
  ${{env.call}}:
    steps:
      - name: GET request
        http:
```
