### DISCUSSION TITLE
Grpc tests headers definition in yaml

### DISCUSSION THREAD

**Discussion by EGYG33K** [stepci/stepci#118] [Q&A] [answered]
Hi everyone,
First of all thank you for the cool tool. I have a problem as my gRPC tests require headers and i tried to define them in the metadata section like

```yaml
version: "1.0"
name: gRPC service template
env:
  host: localhost:9090
  tenant: tenant1
tests:
  example:
    name: Employees tests
    continueOnFail: true
    steps:
      - name: Get Employee by last name
        grpc:
          proto:
            - public/EmployeeService.proto
          host: ${{env.host}}
          service: com.atoss.template.servicetemplate.adapter.handler.grpc.employee.v1.EmployeeService
          method: getEmployeesByLastName
          metadata:
            - X-Tenant-ID: tenant1
          data:
            lastName: Babanu
          headers:
            X-Tenant-ID: {{env.tenant}}
          check:
            jsonpath:
              $.firstName: "Fane"
```

But the header is not sent with the request. I was just wondering if stepci support defining headers for gRPC calls or maybe there is something wrong on my definition. Thank you in advance.

Best regards,
Samy

**Comment by mishushakov** [comment]
Have you tried this?

```yaml
version: "1.0"
name: gRPC service template
env:
  host: localhost:9090
  tenant: tenant1
tests:
  example:
    name: Employees tests
    continueOnFail: true
    steps:
      - name: Get Employee by last name
        grpc:
          proto:
            - public/EmployeeService.proto
          host: ${{env.host}}
          service: com.atoss.template.servicetemplate.adapter.handler.grpc.employee.v1.EmployeeService
          method: getEmployeesByLastName
          metadata:
            X-Tenant-ID: tenant1
          data:
            lastName: Babanu
          check:
            jsonpath:
              $.firstName: "Fane"
```
