### DISCUSSION TITLE
How to check array of objects in response

### DISCUSSION THREAD

**Discussion by kameyama** [stepci/stepci#136] [Q&A]
HI, 

I would like to check array of objects in response.
If I have the following json, how should I write the check block in workflow.yaml?

```json
{
  "data": [
    {
      "id": 1234,
      "platform": "google"
    },
    {
      "id": "5678",
      "platform": "amazon"
    }
  ]
}
```

**Comment by mishushakov** [comment]
You can try following JSONpath:

`$.data[0].id`

here's an online tester: https://jsonpath.com

**Reply by mishushakov** [reply]
You could also capture the content using captures and then check it using the json check
Docs: https://docs.stepci.com/reference/workflow-syntax.html

**Reply by kameyama** [reply]
Thank you for your answer!


I tried using JSONpath to validate the type of all elements but it didn't work as I expected.

For example, for the response written above, the first type of id in the array is number and the second type is string, so I want to create a workflow.yaml that fails at the second.

The results of setepci and tried workflow.yaml are below. I expect all_elements to fail, but it passes.

 How can I fix this?

```shell
❯ stepci run demo.yml

ⓘ  Anonymous usage data collected. Learn more on https://step.ci/privacy

 PASS  all_elements ⏲ 0.032s ⬆ 0 bytes ⬇ 0 bytes
 PASS  first_n_elements ⏲ 0.03s ⬆ 0 bytes ⬇ 0 bytes
 PASS  first ⏲ 0.031s ⬆ 0 bytes ⬇ 0 bytes
 FAIL  second ⏲ 0.031s ⬆ 0 bytes ⬇ 0 bytes

Summary

  ✕ second failed after 0.031s

● second › second

Request  HTTP

GET http://localhost:8000/data HTTP/1.1

Response

HTTP/1.1 200 OK
date: Fri 30 Jun 2023 08:13:15 GMT
server: uvicorn
content-length: 76
content-type: application/json

{"data":[{"id":1234,"platform":"google"},{"id":"5678","platform":"amazon"}]}

Checks

JSONPath

  ✕ $.data[1].id: 5678 (expected [object Object])
  ✔ $.data[1].platform: amazon

Tests: 1 failed, 3 passed, 4 total
Steps: 1 failed, 0 skipped, 3 passed, 4 total
Time:  0.437s, estimated 0s
CO2:   0.00011g

Workflow failed after 0.437s
Give us your feedback on https://step.ci/feedback
```

- demo.yaml
```yaml
version: "1.1"
name: Demo of API tests
env:
  protocol: http
  host: 'localhost:8000'

tests:

  all_elements:
    steps:
      - name: all
        http:
          url: ${{env.protocol}}://${{env.host}}/data
          method: GET
          check:
            jsonpath:
              $.data[*].id:
                - isNumber: true 
              $.data[*].platform:
                - isString: true 

  first:
    steps:
      - name: first
        http:
          url: ${{env.protocol}}://${{env.host}}/data
          method: GET
          check:
            jsonpath:
              $.data[0].id:
                - isNumber: true 
              $.data[0].platform:
                - isString: true 

  second:
    steps:
      - name: second
        http:
          url: ${{env.protocol}}://${{env.host}}/data
          method: GET
          check:
            jsonpath:
              $.data[1].id:
                - isNumber: true 
              $.data[1].platform:
                - isString: true 

  first_n_elements:
    steps:
      - name: all
        http:
          url: ${{env.protocol}}://${{env.host}}/data
          method: GET
          check:
            jsonpath:
              $.data[:100].id:
                - isNumber: true 
              $.data[:100].platform:
                - isString: true 
```
