### DISCUSSION TITLE
How to use custom phone.number format with faker functionality?

### DISCUSSION THREAD

**Discussion by keinsell** [stepci/stepci#213] [Q&A]
I tried refer to https://github.com/stepci/liquidless-faker but there is barely any documentation.

**Comment by slangeder** [comment]
I digged through the code a few days ago to find out how you can pass parameters to the faker filter.

You can find the available faker filters here: https://fakerjs.dev/api/

For phone numbers you can pass a string as format parameter ([Reference](https://github.com/faker-js/faker/blob/7c7f78daa0fef802af916c2f192cc36bee6c88d2/src/definitions/phone_number.ts)):
`${{ phone.number | fake: "!##-!##-####" }}`

If you have to pass an object as parameter, make sure the parameter value is JSON. This means that all parameter names have to be wrapped in double quotes, e.g.:
`${{ internet.email | fake: { "provider": "@example.com" } }}`

**Reply by slangeder** [reply]
@mishushakov If you want, I can create a pull request to update the docs of liquidless-faker.

**Reply by mishushakov** [reply]
Would be very helpful, yes!

**Reply by keinsell** [reply]
I still seem to experience issues with such when I try to provide string parameters.

```
version: "1.1"
name: Phone Number
tests:
  example:
    steps:
            - name: TEST
              http:
                url: https://httpbin.org/anything
                method: POST
                json:
                    phone_number: ${{ phone.phoneNumber | fake: "+48#########" }}
                captures:
                  phone_number:
                    jsonpath: $.phone_number
                  customer_phone_number:
                    jsonpath: $.phone_number
```

On StepCI Playground (landing page) I get error: `e.charAt is not a function`
