### DISCUSSION TITLE
Howto Set A Custom User Agent

### DISCUSSION THREAD

**Discussion by findheld-doug** [stepci/stepci#43] [Q&A] [answered]
Hello, 

I would like to set a custom user agent string and am wondering how I would craft that with stepci?

Thanks,

Doug

**Comment by mishushakov** [comment, marked as answer]
Try something like this:

```yaml
version: "1.1"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://{{env.host}}
          headers:
            user-agent: string
          method: GET
          check:
            status: /^20/
```

Let me know if it solved your question 😉
