### DISCUSSION TITLE
Proposal: Connections

### DISCUSSION THREAD

**Discussion by mishushakov** [stepci/stepci#46] [General]
Useful for storing connection data and persisting connections across test steps

```yml
version: "1.1"
name: gRPC API
tests:
  example:
    connections:
      example:
        grpc:
          proto: public/helloworld.proto
          host: 0.0.0.0:50051
          tls: {}
    steps:
      - name: gRPC request
        grpc:
          # Using a reference
          connection: example
          service: helloworld.Greeter
          method: SayHello
          data:
            name: world!
          check:
            jsonpath:
              $.message: Hello world!
      - name: gRPC request
        grpc:
          # Inline
          connection:
            proto: public/helloworld.proto
            host: 0.0.0.0:50051
            tls: {}
          service: helloworld.Greeter
          method: SayHello
          data:
            name: world!
          check:
            jsonpath:
              $.message: Hello world!
```
