### DISCUSSION TITLE
Proposal: Scripts

### DISCUSSION THREAD

**Discussion by mishushakov** [stepci/stepci#47] [General]
Pre-request, teardown  and checks script support

Example:

```yaml
version: "1.1"
name: Status Check
tests:
  example:
    steps:
      - http:
          url: https://example.com
          method: GET
          hooks:
            beforeRequest:
              - example.js
            afterRequest:
              - example2.js
          check:
            status: /^20/
            custom:
              - example3.js
```

The scripts can then be loaded from the command line:

```
stepci run workflow.yml --scripts=./scripts
```
