### DISCUSSION TITLE
Is there way for run all yml files in folder?

### DISCUSSION THREAD

**Discussion by LemonDouble** [stepci/stepci#61] [Q&A] [answered]
Hello.
I'm trying to use stepci on E2E test after deploying new version of api server.

In api server, we have multiple routers (controllers), 
so i want to make multiple workflow.yml file for each routers.

for example,
UserController -> user-controller-test.yml
OrderContoller -> order-contoroller-test.yml
CategoryController -> category-controller-test.yml

So, Is there has an option to pass multiple .yml files or folders to stepci?
for example, if i type `stepci run --folder test/stepci` then i want run all workflows at once.

I alredy know i can use multiple workflow like this,

```yaml
on: [push]
jobs:
  api_test:
    runs-on: ubuntu-latest
    name: API Tests(user_api)
    steps:
      - uses: actions/checkout@v3
      - name: Step CI Action (User)
        uses: stepci/stepci@main
        with:
          workflow: "test/stepci_test/user-controller-test.yml"
      - name: Step CI Action (Order)
        uses: stepci/stepci@main
        with:
          workflow: "test/stepci_test/order-contoller-test.yml"
```

But in this case,
when developer adding some new testing yml file, then the developer must change workflow files also.

so, if stepci has folder arguments, i think it will more comfortable to use :) 

---

Then.. Is there is any options to run all yml files in folder?

if not, can i contribute that? (I'm not sure i can do it well, but i want to trying to :) )
