### DISCUSSION TITLE
Setting a delay between tests

### DISCUSSION THREAD

**Discussion by gregorojstersek** [stepci/stepci#77] [Q&A] [answered]
Hi!

I would like to ask, if it's possible to set a delay between tests?

Like:

```
steps:
      - name: createUser
      - delay
      - name: updateUser
```

**Comment by mishushakov** [comment]
Do you have a use-case where this would be useful?

**Reply by gregorojstersek** [reply]
I do.

- send a request (test createUser)
    - side effect happens, that creates a certain entity (createAccount)
- get that newly created entity (test getAccount)

Without delay, I'm not able to get that newly created entity.

**Reply by mishushakov** [reply]
Cool, I'll consider adding it
How do you test this currently?

**Reply by gregorojstersek** [reply]
I don't. I tried putting some more tests in between, but I'm not getting consistent results. The results seem to be flaky - sometimes it works / sometimes not unfortunately.

**Comment by AndrewFarley** [comment]
I could see this could be useful in certain systems (like AWS) which follow an eventual consistency model.  There's a possible different way to solve this because a delay isn't a guarantee that the user is created.  Perhaps there's a way to solve this by having a step which is a "validation/check" step which allows repeating (in this case, to try to GET the /user object every few seconds.  Sorry if this is already possible, if it is it isn't obvious.

Example...

```yaml
version: "1.1"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - name: CREATE user
        http:
          url: https://${{env.host}}/
          method: POST
          contents: {username: 123, password: 123}
          check:
            status: /^20/
      - check: Validate user exists
        http:
          url: https://${{env.host}}/123
          method: GET
          check:
            status: /^20/
         retry:
            interval: 3s
            timeout: 10s
            max_retries: 10         
```

**Reply by mishushakov** [reply]
Love the Idea!
Indeed, I'm thinking of adding retries, but I'll first have to consider which changes are required to our code-base

**Comment by sebastianwis** [comment]
Hey Farley @AndrewFarley and @gregorojstersek 
Thank you once again for your contribution here! 
It would be amazing to welcome you to our Discord if you haven't joined it yet: 
https://discord.com/invite/KqJJzJ3BTu
This is where we keep users up to date with updates, features and bug resolutions.

**Comment by mishushakov** [comment, marked as answer]
Hey @gregorojstersek we have just added a delay step type

Example:

```yaml
version: "1.1"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://${{env.host}}
          method: GET
          check:
            status: /^20/
      - delay: 1s
```
