### DISCUSSION TITLE
Comparing response between two URLs

### DISCUSSION THREAD

**Discussion by mmahut** [stepci/stepci#99] [Ideas]
I would be useful, if you could compare the response between two hosts, just to make sure it isn't different but not predefining it.

**Comment by mishushakov** [comment]
That's a neat idea. Do you also want to compare headers, etc.? I have just added a `body` capture type so you can capture the whole response body. Here's an example how you could compare two responses:


```yaml
version: "1.1"
name: Validating JSON
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://jsonplaceholder.typicode.com/posts/1
          method: GET
          captures:
            body1:
              body: true
      - name: GET request
        http:
          url: https://jsonplaceholder.typicode.com/posts/1
          method: GET
          captures:
            body2:
              body: true
          check:
            captures:
              body2: ${{captures.body1}}
```
