### ISSUE TITLE
[Bug]: Int caputres are resent as strings / YAML parsing capabilities

### ISSUE THREAD

**Issue by qbart** [stepci/stepci#131]
### What happened?

I am capturing a number from json response. Capture value is an integer primitive,
in the next step I am sending the value using template but it fails (my service is strict about types) because integer capture is converted back to string.

### What did you expect to happen?

Integer captures should be sent as integers, not strings.
Alternatively templating engine should provide functions for converting strings to numbers.
If nothing from above is possible, YAML parsing should allow for explicit types definition like this: https://www.educative.io/answers/how-to-represent-different-basic-data-types-in-yaml

### Version

2.6.6

### Environment

Node v18.12.1

### How can we reproduce this bug?

workflow file:
```yaml
name: ABC
env:
  host: localhost:4000
tests:
  describe_toy:
    steps:
      - name: Get next toy
        http:
          url: http://${{env.host}}/api/toys/new
          method: POST
          headers:
            Content-Type: application/json
          captures:
            toy_id:
              jsonpath: $.toy_id
          check:
            status: 200
            jsonpath:
              $.toy_id:
                - isNumber: true
              $.text:
                - isString: true

      - name: Generate upload URL
        http:
          url: http://${{env.host}}/api/toys
          method: POST
          headers:
            Content-Type: application/json
          json:
            toy_id: ${{ captures.toy_id }}
          check:
            status: 201

```

First step passes all the checks including:
- toy_id is number

Next step fails:
```yaml
          json:
            toy_id: ${{ captures.toy_id }}
```
because this capture sends string representation of a number e.g.:`"100"`, I expect simple number `100`.

Is there a way to force this behavior or this counts as a bug?

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
Great issue, thanks! Will see what we can do
Sorry for the wait 🙏

**Comment by mishushakov** [comment]
Ok, the issue was in the templating engine. Should be fixed now!

**Comment by mishushakov** [comment]
We have added `toInt`, `toFloat` filters to help you convert the values

**Comment by sebastianwis** [comment]
Hi @qbart 
Thank you for your contribution here! 
It would be amazing to welcome you to our Discord if you haven't joined it yet: 
https://discord.com/invite/KqJJzJ3BTu
This is where we keep users up to date with updates, features and bug resolutions.

**Comment by alenaksu** [comment]
@mishushakov I'm experiencing the same issue in a very similar scenario and using `toInt` didn't help.
I think that's because, no matter what, expressions are always converted to a string (see [here](https://github.com/stepci/liquidless/blob/main/src/index.ts#L57) and [here](https://github.com/stepci/liquidless/blob/main/src/index.ts#L41))

**Comment by mishushakov** [comment]
Do you have a possible fix in mind?

**Comment by alenaksu** [comment]
A possible fix could be returning the actual value when there is just one expression in the string.

For example, given `captures.id === 123`

```yaml
prop1: ${{ captures.id }}
prop2: "${{ captures.id }}"
prop3: ${{ captures.id }} ${{ captures.id }}
prop4: Test ${{ captures.id }}
```

translates to:

```yaml
prop1: 123
prop2: "123"
prop3: "123 123"
prop4: "Test 123"
```

What do you think? I'd be happy to help with a PR if you think this may be a good solution
