### ISSUE TITLE
[Bug]: trpc mutation procedures do not receive arguments from test.

### ISSUE THREAD

**Issue by smoove** [stepci/stepci#132]
### What happened?

I have this test:

```yaml
tests:
  - name: myprocedure
    http:
      url: ${{env.url}}
      headers:
        x-api-key: ${{secrets.apikey}}
      trpc:
        mutation:
          subrouter.myprocedure:
            some: 'asdf'
            arguments: 11234
      check:
        status: /^20/
```

Running it results in the following error:
```
code: "invalid_type",
expected: "object"
received: "undefined"
path: []
```

It seems like the procedure does not receive the arguments defined in the test.

### What did you expect to happen?

I expect the test to pass on the arguments to the trpc procedure.

### Version

2.6.6

### Environment

v16.18.1

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
