### ISSUE TITLE
[Bug]: only the leading digit of the parameter value is sent

### ISSUE THREAD

**Issue by hibohiboo** [stepci/stepci#134]
### What happened?

there is a bug where only the leading digit of the parameter value is sent.
In the example below, the id is sent as 7 instead of 7d8bb386-0f86-4dff-be34-86bb2f55b3662.  

```
version: "1.1"
name: Status Check
env:
  host: http://127.0.0.1:3000
tests:
  scenario1:
    steps:
      - name: GET Scenario
        http:
          url: ${{env.host}}/api/scenario
          method: GET
          params:
            id: 7d8bb386-0f86-4dff-be34-86bb2f55b3662
```

My environment is Windows 10 Home.

### What did you expect to happen?

I expected all the values specified in the parameters to be sent.

### Version

2.6.6

### Environment

v18.16.0

### How can we reproduce this bug?

```
version: "1.1"
name: Status Check
env:
  host: http://127.0.0.1:3000
tests:
  scenario1:
    name: 正常系:シナリオ作成
    steps:
      - name: GET シナリオの取得
        http:
          url: ${{env.host}}/api/scenario
          method: GET
          params:
            id: 7d8bb386-0f86-4dff-be34-86bb2f55b3662
          check:
            status: /^20/
            jsonpath:
              $[0].id: x7d8bb386-0f86-4dff-be34-86bb2f55b3662
              $[0].title: テスト用シナリオ
```

### Relevant log output

```shell
{
  "body": null,
  "headers": {
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "close",
    "Host": "127.0.0.1:3000",
    "User-Agent": "got (https://github.com/sindresorhus/got)",
    "X-Forwarded-Port": "3000",
    "X-Forwarded-Proto": "http"
  },
  "httpMethod": "GET",
  "isBase64Encoded": false,
  "multiValueHeaders": {
    "Accept-Encoding": [
      "gzip, deflate, br"
    ],
    "Connection": [
      "close"
    ],
    "Host": [
      "127.0.0.1:3000"
    ],
    "User-Agent": [
      "got (https://github.com/sindresorhus/got)"
    ],
    "X-Forwarded-Port": [
      "3000"
    ],
    "X-Forwarded-Proto": [
      "http"
    ]
  },
  "multiValueQueryStringParameters": {
    "id": [
      "7"
    ]
  },
  "path": "/api/scenario",
  "pathParameters": null,
  "queryStringParameters": {
    "id": "7"
  },
  "requestContext": {
    "accountId": "123456789012",
    "apiId": "1234567890",
    "domainName": "127.0.0.1:3000",
    "extendedRequestId": null,
    "httpMethod": "GET",
    "identity": {
      "accountId": null,
      "apiKey": null,
      "caller": null,
      "cognitoAuthenticationProvider": null,
      "cognitoAuthenticationType": null,
      "cognitoIdentityPoolId": null,
      "sourceIp": "127.0.0.1",
      "user": null,
      "userAgent": "Custom User Agent String",
      "userArn": null
    },
    "path": "/api/scenario",
    "protocol": "HTTP/1.1",
    "requestId": "7307e3bc-f1e2-4858-bc5f-abbf72941e6b",
    "requestTime": "11/Jun/2023:15:57:43 +0000",
    "requestTimeEpoch": 1686499063,
    "resourceId": "123456",
    "resourcePath": "/api/scenario",
    "stage": "v1"
  },
  "resource": "/api/scenario",
  "stageVariables": null,
  "version": "1.0"
}
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
