### ISSUE TITLE
[Feature Request] Reuse test ref'd via JSON pointer URL inside other tests

### ISSUE THREAD

**Issue by matmar10** [stepci/stepci#140]
# Background
First off: love the framework! We're actively migrating a relatively large project from a [niche yaml-based framework called rest-ez](https://github.com/blossomfinance/rest-ez) (originally called "justapi") to stepci. So far, we're happy with stepci and no looking back.

There's a lot that stepci gets right - out of the box. I'm wondering if  there is scope for reusing entire steps?

This is something we'd be willing to offer corporate sponsorship (LaunchGood.com). Please email me: matthew (at) launchgood.com if this is something the team is interest in.  Sponsorship could be cash or contribution of developer resources. Let me know!

Keep up the great work!

# Feature Suggestion

**Allow reusing entire test definitions in other tests, via JSON pointer URL**

The docs note that each test must have a _unique name_ - this (in theory) could make implementation of this easier!

For example, some common pre-req. operations:

1. Register a new randomly generated user (via faker)
2. Verify email
3. Add an address to the user
4. Add a credit card

These could be referenced by test name to be re-used in other tests.

Define these re-usable tests:

`tests/user/onboarding.yml`

```yaml
tests:
  createNewUser: 
    steps: 
      - name: Create new user
         http:
           url: ${{env.baseUrl}}/user
           method: POST
          headers:
            - Accept: application/json
            - Content-Type: application/json
          json:
            email: ${{ internet.email | fake }}
            password: ${{ internet.password | fake }}
  verifyUserEmail: 
    steps:
      - name: Verify user's email via link sent to inbox
         http: # ...  etc
         ...
  addUserAddress:
    steps:
      - name: Verify user's email via link sent to inbox
         http: # ...  etc
         ...
  addUserCreditCard:
    steps:
      - name: Verify user's email via link sent to inbox
         http: # ...  etc
```

Use them inside a suite (or other tests):

`tests/cart/checkout.yml`

```yaml
tests:
  # test keys that point to strings are treated as JSON pointers into those docs
  createNewUser: './../user/onboarding.yml#tests/createNewUser'
  verifyUserEmail: './../user/onboarding.yml#tests/verifyUserEmail'
  addUserAddress: './../user/onboarding.yml#tests/addUserAddress'
  addUserCreditCard: './../user/onboarding.yml#tests/addUserCreditCard'
  addToCartCheckout: 
     steps: 
       - name: Add random item to cart
         http: # ...  etc
       - name: Complete purchase
          http: # ... etc
```

## Other considerations

- Make sure captures carry over
- Passing state between tests

**Comment by sebastianwis** [comment]
Hi Matthew,

Thanks for the feature-request and the encouragement.
I've sent you a mail. :)

**Comment by sebastianwis** [comment]
Hey Matthew,

Is this still a priority for you?
We haven't heard from you for a while.

**Comment by mishushakov** [comment]
This is now supported in runner version 1.10.11

Example:

```yaml
version: "1.1"
name: Refs
tests:
  example:
    $ref: "test.yml"
```

Re-using steps:

```yaml
version: "1.1"
name: Basic Auth
tests:
  example:
    steps:
      - $ref: "step.yml"
```

Works the same way as in OpenAPI spec

**Comment by matmar10** [comment]
Amazing work @mishushakov!

**Comment by matmar10** [comment]
For those looking to use this feature, just note that the re-usable step file is an individual step:

```Yaml
name: Register a New User
http:
  url: /register
  method: POST
  headers:
    Content-Type: application/json
  json:
    email: mish.is@awesome.com
  check:
    status: 201
    jsonpath:
      $.id: /^[0-9]+$/
      $.email: mish.is@awesome.com
```

Either myself or @nabeelakhtar-10p will contribute a docs update for this.
