### ISSUE TITLE
[Bug]: env not available in config

### ISSUE THREAD

**Issue by matmar10** [stepci/stepci#144]
### What happened?

In a suite:
```yaml
version: '1.1'
name: My Little REST API Pony
config:
  http:
    baseURL: ${{ env.BASE_URL }}
    
tests:
  createUser:
    steps:
      - name: Register
        http:
          url: /user
          method: POST
        # ...  etc ...
```

To be run via: 
```Bash
stepci run test/my-suite-little-rest-api-pony.yml --env BASE_URL="http://localhost:3000"
```

### What did you expect to happen?

Docs seem to suggest the templating and environment variables are generally available everywhere. 

I hope it's glaringly obvious from the example how elegant the test steps become when you can use the `config.http.baseURL`. 

But if we're not able to connect this to the environment variables, we cannot run this against different servers (e.g. local dev, staging, production)

### Version

2.6.8

### Environment

v16.16.0

### How can we reproduce this bug?

Workflow provided above.

### Relevant log output

```shell
Invalid URL
```

### Would you be interested in working on a bugfix for this issue?

- [X] Yes! Assign me
