### ISSUE TITLE
[Bug]: Descriptive JSON Schema error objects

### ISSUE THREAD

**Issue by JavierSierraBlazquez** [stepci/stepci#183]
### What happened?

JSON Schema error shows [object Object] in both given and expected objects.

![image](https://github.com/stepci/stepci/assets/26868500/30cf69c3-8f7f-471e-b9d2-ee29c2ab0bf8)

### What did you expect to happen?

It would be helpful to the user showing objects content in the error. In this way, the user sees why the error occurs.

I made a first approach by adding a `JSON.stringify` in `render.ts > renderStep (line 108)`
```
: console.log(renderSpaces(2) + chalk.red('✕ ') + chalk.red(JSON.stringify(checks[check].given)) + ' expected: ' + chalk.green(JSON.stringify(checks[check].expected)))
```

![image](https://github.com/stepci/stepci/assets/26868500/85ad36c6-f77d-4d14-8fb9-2c3e58fc7195)

I have taken the liberty of adding colors, but i'm not sure if it is wanted.

Also I see more console.log in the same function that may be reviewed for the same problem.

I'm open to contribute, but I would like to hear your opinions first!

### Version

2.7.0

### Environment

Node v18.18.0

### How can we reproduce this bug?

Simple workflow file:
```
version: '1.0'
name: Hello World API
config:
  http:
    baseURL: http://localhost:1234
tests:
  default:
    name: Default
    steps:
      - name: Returns a greeting message
        http:
          url: /hello
          method: GET
          check:
            status: 200
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
components:
  schemas: null
```

Simple Express API returning a wrong object property "message2" instead expected "message" in the workflow
```
import express from 'express';

const app = express();
const port = 1234;

app.route('/hello').get((req, res) => {
  res.json({ message2: 'string' });
});

app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
});
```

### Would you be interested in working on a bugfix for this issue?

- [X] Yes! Assign me
