### ISSUE TITLE
[Bug]: Array query parameter

### ISSUE THREAD

**Issue by javier-sierra-sngular** [stepci/stepci#190]
### What happened?

The query parameter of type array is not transformed into an array in the request URL.
`[GET] /?singleParameter=true&arrayParameter=true` - Incorrect
`[GET] /?singleParameter=true&arrayParameter[]=true` - Correct

### What did you expect to happen?

If the value is of type array, the URL should contains the appropiate syntax to indicate it.

### Version

2.7.2

### Environment

Node v18.18.0

### How can we reproduce this bug?

Using this workflow will result in the request `[GET] /?singleParameter=true&arrayParameter=true`, where arrayParameter is not an array as specified in the workflow

```yaml
version: "1.0"
name: My API
config:
  http:
    baseURL: http://localhost:1235
tests:
  default:
    name: Default
    steps:
      - http:
          url: /
          method: GET
          params:
            singleParameter: false
            arrayParameter:
              - true
          check:
            status: 0
```

### Would you be interested in working on a bugfix for this issue?

- [x] Yes! Assign me

**Comment by mishushakov** [comment]
It works as expected

```yml
http:
  url: /filter
  method: GET
  params:
    fruits:
      - apple
      - banana  
```

```
/filter?fruits=apple&fruits=banana
```

**Comment by javier-sierra-sngular** [comment]
> /filter?fruits=apple&fruits=banana

It is a bit strange because the same workflow you have provided results me in different output than yours: 
`/filter?fruits=apple%2Cbanana`. 

This is usually interpreted as single string `apple,banana` rather than an array of two elements.

This is the complete workflow I used for this test
```
version: '1.0'
name: My API
config:
  http:
    baseURL: http://localhost:1235
tests:
  default:
    name: Default
    steps:
      - http:
          url: /filter
          method: GET
          params:
            fruits:
              - apple
              - banana
          check:
            status: 0
```
And Step CI version is 2.7.2

**Comment by javier-sierra-sngular** [comment]
The **main problem** is when you specify a **single element array**. 

The fact is when a workflow is built using a single array parameter, Step CI make the request and the resulting URL may cause validation errors in the API. Because it is waiting for an array but a single string value is received.

I know there are many ways to represent arrays in a query string and some of them are ambiguous when there are a single element only.

This is an example of how express.js parse url query parameters 
```
/filter?fruits=apple%2Cbanana
{ fruits: 'apple,banana' } // single string :S, this is related to previous comment

/filter?fruits=apple&fruits=banana
{ fruits: [ 'apple', 'banana' ] } // ok when 2+ elements

/filter?fruits=apple
{ fruits: 'apple' } // it is not a single element array

/filter?fruits[]=apple    // this is the best representation IMHO
{ fruits: [ 'apple' ] } 
```

I debugged the application and I see that the parameter searchString is passed as `URLSearchParams` to `got` library. I tested `URLSearchParams.toString()` and it returns the values separated by comma. I wonder if here is the problem.
I also tested to replace URLSearchParams by custom string `'fruits[]=apple'` and it worked like a charm. (src/index.ts:730)

This point to the possible solution commented here https://github.com/sindresorhus/got/issues/1559#issuecomment-747350228 to use like `/filter?fruits[]=apple` representation
`You could also use https://github.com/sindresorhus/query-string and just pass the stringified query parameters to searchParams.`


> Ps. you can still define it manually, no need to use the params shortcut

I am not writing the workflow manually, it is generated by plugin-openapi that uses params

**Comment by mishushakov** [comment]
Would you be able to contribute a fix?

**Comment by javier-sierra-sngular** [comment]
Sure, I will work in a PR

**Comment by mishushakov** [comment]
My example above was incorrect

```yaml
http:
  url: /filter
  method: GET
  params:
    fruits:
      - apple
      - banana  
```

produces:

```
/filter?fruits=apple%2Cbanana
```

while this:

```
http:
  url: /filter
  method: GET
  params:
    -
      - 'fruits'
      - 'apple'
    -
      - 'fruits'
      - 'banana'
```

produces:

```
/filter?fruits=apple&fruits=banana
```
