### ISSUE TITLE
[Bug]: `faker_1.faker[module][type] is not a function`

### ISSUE THREAD

**Issue by keinsell** [stepci/stepci#194]
### What happened?

When used `stepci run workflow.yml` on my workflow file it crashed.

```yml
version: "1.1"
name: Account Registration
env:
  protocol: http
  host: localhost
  port: 45483
tests:
  register-account:
    steps:
      - name: POST /account/
        http:
          url: ${{env.protocol}}://${{env.host}}:${{env.port}}/account
          method: POST
          check:
            status: /^20/
          headers:
            Content-Type: application/json
          json:
            username: ${{ internet.username | fake }}
            password: fasasfaasdasdasd
            email: kasdasdasdads
```

### What did you expect to happen?

Generate fake data instead crashing

### Version

2.7.2

### Environment

v21.4.0

### Relevant log output

```shell
ⓘ  Anonymous usage data collected. Learn more on https://step.ci/privacy

(node:142664) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 FAIL  register-account ⏲ 0s ⬆ 0 bytes ⬇ 0 bytes

Summary

  ✕ POST /account/ failed after 0s

⚠︎ register-account › POST /account/

faker_1.faker[module][type] is not a function


Tests: 1 failed, 0 passed, 1 total
Steps: 1 failed, 0 skipped, 0 passed, 1 total
Time:  0.012s, estimated 0s
CO2:   0.00000g

Workflow failed after 0.012s
Give us your feedback on https://step.ci/feedback
 ERROR  Command failed with exit code 5: stepci run ./account.workflow.yml

pnpm: Command failed with exit code 5: stepci run ./account.workflow.yml
    at makeError (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:24242:17)
    at handlePromise (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:24813:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:223506:7)
    at async /usr/lib/node_modules/pnpm/dist/pnpm.cjs:232908:21
    at async main (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:232875:34)
    at async runPnpm (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:233130:5)
    at async /usr/lib/node_modules/pnpm/dist/pnpm.cjs:233122:7
```
```


### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
