### ISSUE TITLE
TRPC mutartion batching

### ISSUE THREAD

**Issue by UndefinedBehaviour** [stepci/stepci#199]
I tried to run a batched mutation in TRPC like this:

```
...
        steps:
            - name: trpc mutation batching
              http:
                  url: ${{env.url}}
                  trpc:
                      mutation:
                          - createObject:
                                json:
                                   { name: 'Bob' }
                          - createObject:
                                json:
                                   { name: 'Jack' }
                  check:
                      status: 200
```
I got an error like "No \"mutation\"-procedure on path ..."
Am I doing something wrong or that's not supported yet?
