### ISSUE TITLE
[Bug]: Error of `input` must not start with a slash when using `prefixUrl`

### ISSUE THREAD

**Issue by Century-ss** [stepci/stepci#204]
### What happened?

When running a workflow using config.http.baseURL, 
I get an error 「`input` must not start with a slash when using `prefixUrl`」.

### What did you expect to happen?

Because the config parameter is not passed to runHTTPStep, 
config?.http?.baseURL is undefined and the URL cannot be created using baseURL and starts with a slash.
https://github.com/stepci/runner/blob/6619c1cc6914a15547367ad1792240534c3b7389/src/index.ts#L360
https://github.com/stepci/runner/blob/6619c1cc6914a15547367ad1792240534c3b7389/src/steps/http.ts#L190-L197

### Version

stepci:2.8.0, @stepci/runner:2.0.0 

### Environment

Node v18.19.0

### How can we reproduce this bug?

- Rewrite the workflow in basic.yml with the following data
```yml
version: '1.0'
name: Test API definition
config:
  http:
    baseURL: https://petstore.swagger.io/v2
tests:
  default:
    name: Default
    steps:
      - name: test api step
        http:
          url: /store/inventory
          method: GET
          check:
            status: 200
            schema:
              type: object

```
- In the root directory of @stepci/runner, `npm run test`

### Relevant log output

```shell
=> % npm run test                                                                                                                                                                        

> @stepci/runner@2.0.0 test
> ts-node ./tests/test.ts

[
  {
    id: undefined,
    testId: 'default',
    name: 'test api step',
    timestamp: 2024-02-19T08:52:28.354Z,
    passed: false,
    errored: true,
    skipped: false,
    duration: 3,
    responseTime: 0,
    bytesSent: 0,
    bytesReceived: 0,
    co2: 0,
    errorMessage: '`input` must not start with a slash when using `prefixUrl`',
    type: undefined,
    request: undefined,
    response: undefined,
    checks: undefined,
    captures: undefined,
    cookies: undefined
  }
]
```

### Would you be interested in working on a bugfix for this issue?

- [X] Yes! Assign me
- I have already created a PR that fixes this problem and would appreciate your confirmation.→https://github.com/stepci/runner/pull/114
