### ISSUE TITLE
[Bug]: Following step containing retries is not terminated on preceding step failure

### ISSUE THREAD

**Issue by BapAtRb** [stepci/stepci#206]
### What happened?

Hey! 👋
I have a simple workflow that contains one test with two steps. It uses API endpoint, where in first step it should trigger resource deletion and second step should perform multiple retries to check if deletion has completed. I have noticed that, even if the first step fails, the workflow waits as long as much time was specified in the retries property of second step. In my case logs (attached) show that the first step failed after ~5 seconds. Second step was skipped due to mentioned failure but workflow finished after 186 seconds (6 retries with 30 seconds interval - please see attached workflow).

### What did you expect to happen?

I expect that test fails immediately after given step failure without picking up retries setting (as a matter of fact - anything) configured in following steps.

### Version

v2.8.0

### Environment

v20.11.1

### How can we reproduce this bug?

```
version: "1.1"
name: Deletion workflow
tests:
  test1:
    steps:
      - name: Delete
        http:
          url: <redacted>
          method: DELETE
          auth:
            $ref: auth.stepci.yml
          check:
            status: 202
      - name: Check status
        retries:
          count: 6
          interval: 30s
        http:
          url: <redacted>
          method: GET
          auth:
            $ref: auth.stepci.yml
          check:
            status: 404
```

### Relevant log output

```shell
Summary

  ✕ Delete failed after 4.974s
  ⚠︎ Check status skipped after 0s

<verbose output redacted>

Tests: 1 failed, 0 passed, 1 total
Steps: 2 failed, 1 skipped, 0 passed, 2 total
Time:  186.216s, estimated 186s
CO2:   0.00010g
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
