### ISSUE TITLE
[Bug]: `env` not available in `$ref`

### ISSUE THREAD

**Issue by RemiBardon** [stepci/stepci#220]
### What happened?

I'm writing integration tests. To make sure that the API returns schemas as defined in the OpenAPI description file, I'm using `check: schema: $ref`. I'd like to reference the file exposed by the API itself, as in the examples given by [swagger.io/docs/specification/using-ref](https://swagger.io/docs/specification/using-ref/). For convenience, I'd like to use `${{ env.host }}`, but it seems like the value isn't replaced before Step CI searches for the reference.

### What did you expect to happen?

I was expecting `${{ env.host }}/openapi.yaml` to be replaced by `https://petstore3.swagger.io/api/v3/openapi.yaml` and the file being found.

This issue relates to #144.

### Version

2.8.1

### Environment

Node v22.2.0

### How can we reproduce this bug?

```yaml
version: "1.1"
name: Bug report
env:
  host: https://petstore3.swagger.io/api/v3
tests:
  example:
    steps:
      - http:
          method: POST
          url: ${{ env.host }}/user
          headers:
            Content-Type: application/json
          json: {
            "id": 10,
            "username": "theUser",
            "firstName": "John",
            "lastName": "James",
            "email": "john@email.com",
            "password": "12345",
            "phone": "12345",
            "userStatus": 1
          }
          check:
            schema:
              $ref: ${{ env.host }}/openapi.yaml#/components/schemas/User
```

```bash
stepci run test.yaml
```

### Relevant log output

```shell
/usr/local/Cellar/stepci/2.8.1/libexec/lib/node_modules/stepci/node_modules/@stepci/runner/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/file.js:52
            reject(new ResolverError(ono(err, `Error opening file "${path}"`), path));
                   ^

ResolverError: Error opening file "/Users/me/project/${{ env.host }}/openapi.yaml"
ENOENT: no such file or directory, open '/Users/me/project/${{ env.host }}/openapi.yaml'
    at ReadFileContext.callback (/usr/local/Cellar/stepci/2.8.1/libexec/lib/node_modules/stepci/node_modules/@stepci/runner/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/file.js:52:20)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:300:13) {
  code: 'ERESOLVER',
  source: '/Users/me/project/${{ env.host }}/openapi.yaml',
  path: null,
  toJSON: [Function: toJSON],
  ioErrorCode: 'ENOENT',
  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
}

Node.js v22.2.0
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
