### ISSUE TITLE
[Bug]: OAuth token request uses incorrect content-type

### ISSUE THREAD

**Issue by ghost** [stepci/stepci#237]
### What happened?

When using the OAuth option for http steps, the token request is done with a JSON body and results in a `400 Bad Request` for tested identity providers.

Also an optional `scope` parameter currently can't be defined, which is necessary for some IdPs and APIs.

### What did you expect to happen?

According to [The OAuth 2.0 Authorization Framework - Client Credentials Grant flow](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2) the request is to be made with `content-type: application/x-www-form-urlencoded`.

It would be nice if the oauth schema in the step specification could follow the openApi security schemes schema, so it can simply be referenced.

### Version

2.8.2

### Environment

Node v18.16.0

### How can we reproduce this bug?

```
version: "1.1"
name: OAuth
tests:
  example:
    steps:
      - http:
          url: https://example.com/protected
          method: GET
          auth:
            oauth:
              endpoint: "https://app.auth0.com/oauth/token"
              client_id: ""
              client_secret: ""
              audience: ""
```

### Would you be interested in working on a bugfix for this issue?

- [X] Yes! Assign me
