### ISSUE TITLE
[Bug]: Incorrect types in schema.json

### ISSUE THREAD

**Issue by RemiBardon** [stepci/stepci#240]
### What happened?

For some reason, I have to use `# yaml-language-server: $schema=https://raw.githubusercontent.com/stepci/stepci/main/schema.json` in my Step CI files in Zed. However, when doing so I get errors:

- `Incorrect type. Expected "string".` on `http.params.<param>` using `int` (which is supported)
- `Incorrect type. Expected "object".` on `http.params` using `string` (which is supported)

### What did you expect to happen?

No error.

### Version

main→e9af898c60711fca6d2c0b5e0003e4cfd63d7e50

### Environment

ø

### How can we reproduce this bug?

Open this YAML file in a text editor supporting modeline:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/stepci/stepci/main/schema.json

version: "1.1"
name: "Step CI #240"
tests:
  whatever:
    name: Default
    steps:
      - name: Unsupported int
        http:
          method: GET
          url: /whatever
          params:
            foo: 1
      - name: Unsupported string
        http:
          method: GET
          url: /whatever
          params: "foo=1&bar=2"
```

You should see errors on `1` and `"foo=1&bar=2"`

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
