### ISSUE TITLE
[Bug]: fake filter does not applies on env variables inside `tests.<test>.env`

### ISSUE THREAD

**Issue by gabplch** [stepci/stepci#242]
### What happened?

Fake filter does not applies on env variables inside `tests.<test>.env`, so it sets like `${{ string.uuid | fake }}`

### What did you expect to happen?

`some-uuid` for e.g.

### Version

2.8.2

### Environment

Node 22.6.0

### How can we reproduce this bug?

```yaml
tests:
  example:
    env:
      uuid: ${{ string.uuid | fake }}
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
