### ISSUE TITLE
[Bug]: No able to check for the redirects

### ISSUE THREAD

**Issue by matteo-cristino** [stepci/stepci#243]
### What happened?

Using 
```
tests.<test>.steps.[step].http.check.redirects
```
in a test I got the error
```
Cannot use 'in' operator to search for 'eq' in ...
```

### What did you expect to happen?

The redirects should be checked correctly

### Version

2.8.2

### Environment

Node v20.14.0

### How can we reproduce this bug?

 ```yaml
- name: redirect
   http:
     url: https://httpbin.org/redirect-to?url=https://example.com&status_code=301
     method: GET
     check:
       redirects:
         - https://example.com
```
results in:
```
Cannot use 'in' operator to search for 'eq' in https://example.com
```

At the moment I found this workaround to test it:
 ```yaml
- name: redirect
   http:
     url: https://httpbin.org/redirect-to?url=https://example.com&status_code=301
     method: GET
     followRedirects: false
     check:
       headers:
         Location: https://example.com
       status: 301
```
that passes the test

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
