### ISSUE TITLE
[Bug]: Session cookie received but not sent in subsequent steps

### ISSUE THREAD

**Issue by Phalisyle** [stepci/stepci#244]
### What happened?

I am testing API requests and encountered an issue with session cookies. During a authentication request, the server sends back a session cookie, which is properly received and displayed in stepci. However, in subsequent requests the session cookie is not being sent back to the server.

The server does not recognize any incoming cookies, and upon inspection with Wireshark, I confirmed that no cookies are included in the outgoing request.

### What did you expect to happen?

The session cookie received during the authentication request should be automatically sent in subsequent requests, as it is described in the documentation (https://docs.stepci.com/guides/testing-http.html#cookies)

### Version

2.8.2

### Environment

Node v22.11.0

### How can we reproduce this bug?

This is the part of my workflow.yml:
```yml
- name: authenticate_new_admin
  http:
    url: ${{env.host}}/clinic-admins/login
    method: POST
    json:
      clinic_id: ${{captures.clinic_id}}
      username: ${{captures.clinic_admin}}
      password: ${{captures.clinic_admin_pw}}
    check:
      status: 200
      schema:
        type: object
        session_expires: string
- name: register_test_clinician_true
  http:
    url: ${{env.host}}/auth/clinicians/registration
    method: POST
    json:
      username: Clinician_${{captures.clinic_id}}
    check:
      status: 200
```
`authenticate_new_admin` succeeds and returns the session cookie, `register_test_clinician_true` fails.

- The session cookie is not sent in this request.
- The server does not recognize an authenticated session.
- Inspecting the request using Wireshark shows no cookies in the outgoing request:
![Request_without_cookie](https://github.com/user-attachments/assets/b2bddac2-e48b-43d9-a0ac-84530b6ade40)

### Relevant log output

```shell
✔ test_flow › authenticate_new_admin

Request  HTTP 

Post http://127.0.0.1:8080/api/v2/clinic-admins/login HTTP/1.1
Content-Type: application/json

{"clinic_id":"574779","username":"Admin_574779","password":"tfmMurrfhk"}
Response

HTTP/1.1 200 OK
access-control-allow-methods: PATCHPUTPOSTGETOPTIONSDELETE
access-control-max-age: 3600
access-control-allow-credentials: true
access-control-allow-headers: x-requested-with authorization Content-Type Authorization credential X-XSRF-TOKEN
vary: Origin Access-Control-Request-Method Access-Control-Request-Headers
x-content-type-options: nosniff
x-xss-protection: 0
cache-control: no-cache no-store max-age=0 must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
set-cookie: SESSION=ZTllZDQ2ZjUtZmU0ZS00MDA0LWJlM2ItYjMyZDUwYjVhMjdk; Path=/; Secure; HttpOnly; SameSite=Lax
content-type: application/json
transfer-encoding: chunked
date: Fri 15 Nov 2024 16:22:42 GMT
connection: close

{"session_expires":"2024-11-15T16:37:42.976Z"}

Captures

{
  "clinic_id": "574779",
  "clinic_name": "Clinic_574779",
  "clinic_admin": "Admin_574779",
  "clinic_admin_pw": "tfmMurrfhk"
}

Cookies

[
  {
    "key": "SESSION",
    "value": "ZTllZDQ2ZjUtZmU0ZS00MDA0LWJlM2ItYjMyZDUwYjVhMjdk",
    "domain": "127.0.0.1",
    "path": "/",
    "secure": true,
    "httpOnly": true,
    "hostOnly": true,
    "creation": "2024-11-15T16:22:42.983Z",
    "lastAccessed": "2024-11-15T16:22:42.983Z",
    "sameSite": "lax"
  }
]

Checks

✔ JSON Schema

Expected

{
  "type": "object",
  "session_expires": "string"
}

Given

{
  "session_expires": "2024-11-15T16:37:42.976Z"
}

✔ Status

Expected

200

Given

200

● test_flow › register_test_clinician_true

Request  HTTP 

POST http://127.0.0.1:8080/api/v2/auth/clinicians/registration HTTP/1.1
Content-Type: application/json

{"username":"Clinician_574779"}
Response

HTTP/1.1 403 Forbidden
access-control-allow-methods: PATCHPUTPOSTGETOPTIONSDELETE
access-control-max-age: 3600
access-control-allow-credentials: true
access-control-allow-headers: x-requested-with authorization Content-Type Authorization credential X-XSRF-TOKEN
x-content-type-options: nosniff
x-xss-protection: 0
cache-control: no-cache no-store max-age=0 must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
set-cookie: SESSION=ZDg4YTdhMDYtNzM4ZC00YmNjLTk4MjMtNDc0MjRhMDBkZjA1; Path=/; Secure; HttpOnly; SameSite=Lax
content-type: application/json
transfer-encoding: chunked
date: Fri 15 Nov 2024 16:22:42 GMT
connection: close

{"timestamp":"2024-11-15T16:22:43.005+00:00","status":403,"error":"Forbidden","path":"/api/v2/auth/clinicians/registration"}
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
