### ISSUE TITLE
[Bug]: `stepci/stepci@main` does not work

### ISSUE THREAD

**Issue by MH0386** [stepci/stepci#249]
### What happened?

My GitHub Actions workflow job:
```
...
jobs:
  api_test:
    runs-on: ubuntu-latest
    name: API Test
    services:
      app:
        image: ghcr.io/alphaspheredotai/vocalizr:154-merge
        ports:
          - 7860:7860
    steps:
      - name: Echo URL
        run: echo "app available on localhost:${{ job.services.app.ports['7860'] }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Step CI
        uses: stepci/stepci@main
        with:
          workflow: .github/stepci.yaml
          verbose: true
```
My stepci workflow:
```
version: "1.1"
name: Status Check
env:
  host: localhost:7860
tests:
  app:
    steps:
      - name: GET request
        retries:
          count: 10
          interval: 10s
        http:
          url: http://${{env.host}}/
          method: GET
          timeout: 30s
          check:
            status: /^20/
```

### What did you expect to happen?
```
ⓘ  Anonymous usage data collected. Learn more on https://step.ci/privacy

 PASS  example ⏲ 0.754s ⬆ 147 bytes ⬇ 1026 bytes

Tests: 0 failed, 1 passed, 1 total
Steps: 0 failed, 0 skipped, 1 passed, 1 total
Time:  0.759s, estimated 1s
CO2:   0.00045g

Workflow passed after 0.759s
Give us your feedback on https://step.ci/feedback
```

### Version

2.8.2

### Environment

v22.17.0

### Relevant log output

```
ⓘ  Anonymous usage data collected. Learn more on https://step.ci/privacy
 FAIL  app ⏲ 100.097s ⬆ 0 bytes ⬇ 0 bytes
Summary
  ✕ GET request failed after 0.002s
⚠︎ app › GET request
Tests: 1 failed, 0 passed, 1 total
Steps: 1 failed, 0 skipped, 0 passed, 1 total
Time:  100.131s, estimated 100s
CO2:   0.00000g
Workflow failed after 100.131s
Give us your feedback on https://step.ci/feedback
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
