### ISSUE TITLE
[Bug]: CLI arguments are not being replaced in testing templates

### ISSUE THREAD

**Issue by dstrickland67** [stepci/stepci#57]
### What happened?

We are using JWTs for authentication.   I am testing on macos (M1)

export JWT=$(genJwtToken)
stepci workflow.yml -s JWT=$JWT
 && 
stepci workflow.yml -s JWT=$JWT
{{env.JWT}} in the bearer/token section never gets replaced "sends to testing server [object object]"
{{secrets.JWT}} in the bearer/token section never gets replaced "sends to testing server [object object]"

  auth:
            bearer:
              token: {{secret.JWT}}

 auth:
            bearer:
              token: {{secrets.JWT}}

Now I am using sed to transform the workflow in memory for JWT before running. 

Love the tool.  Also would love to know if I am doing something wrong as well.

### What did you expect to happen?

I expected the test to pass .  Trying to mirror tests out of swagger.

### Version

2.4.5

### Environment

v16.16

### How can we reproduce this bug?

I started with the starting example.  

### Relevant log output

```shell
POST http://localhost:3000/schools/getRoster HTTP/1.1
Content-Type: application/json
Authorization: Bearer secrets.ABCJ

{"schoolId":"8eLtalPcqv5Ioae4E4Wn"}
Response

HTTP/1.1 403 Forbidden
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 33
etag: W/"21-6WgjtJhAT2yQTa63ODczjQj9Xro"
date: Mon 07 Nov 2022 19:25:56 GMT
connection: close

{"message":"Could not authorize"}

Checks

S
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
Thanks for bug report, I'll look into it in a minute

**Comment by dstrickland67** [comment]
That works. 

Thanks,
David

**Comment by mishushakov** [comment]
I have investigated the issue
turns out, YAML does some quirks when `{{ }}` is not in a string

entering

```yaml
{{test}}
```

produces:

```json
{
  "{\"test\"=>nil}": null
}
```

Try yourself: https://www.json2yaml.com

To fix the issue you have to wrap it in quotes, like that:

```
version: "1.1"
name: Basic Auth
env:
  username: hello
  password: world
tests:
  example:
    steps:
      - name: Basic Auth
        http:
          url: https://httpbin.org/basic-auth/hello/world
          method: GET
          auth:
            basic:
              username: "{{ env.username }}"
              password: "{{ env.password }}"
          check:
            status: 200
```

As this is a bit counterintuitive, I'll change the templating syntax to use `${{  }}` instead (like GitHub Actions)
I'll close the issue, as this is not a bug with Step CI per se

Thanks a lot for reporting though 🙏
