### ISSUE TITLE
[Bug]:  continueOnFail doesn't work as expected

### ISSUE THREAD

**Issue by dstrickland67** [stepci/stepci#60]
### What happened?

Seem as though the worflow config for continueOnFail, does not continue.  After looking at the code, it seems to be implemented. I might have defined it in the wrong spot, but if it worked, it would be really handy.

### What did you expect to happen?

I expected all test to run and stop on the first failing test.

### Version

2.4.5

### Environment

node 16.16

### How can we reproduce this bug?

version: "1.1"
name: Status Check
env:
  host: example.com
config:
  continueOnFail: true
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://{{env.host}}1
          method: GET
          check:
            status: /^20/
      - name: GET request
        http:
          url: https://{{env.host}}
          method: GET
          check:
            status: /^20/

### Relevant log output

```shell
Request  HTTP 

POST http://localhost:3000/users/verify-code HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiaXBJZUJJaGJHMllEeGdQNHc1N1B6d0s2WDNJMyIsInVzZXJSZWNvcmQiOnsidWlkIjoiaXBJZUJJaGJHMllEeGdQNHc1N1B6d0s2WDNJMyIsImVtYWlsIjoia2F5ZWoudGFrQGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm1ldGFkYXRhIjp7Imxhc3RTaWduSW5UaW1lIjoiTW9uLCAwNyBOb3YgMjAyMiAxODo1MToyNCBHTVQiLCJjcmVhdGlvblRpbWUiOiJNb24sIDA3IE5vdiAyMDIyIDE4OjUxOjI0IEdNVCIsImxhc3RSZWZyZXNoVGltZSI6IlR1ZSwgMDggTm92IDIwMjIgMDE6Mjc6MzggR01UIn0sInRva2Vuc1ZhbGlkQWZ0ZXJUaW1lIjoiTW9uLCAwNyBOb3YgMjAyMiAxODo1MToyNCBHTVQiLCJwcm92aWRlckRhdGEiOlt7InVpZCI6ImtheWVqLnRha0BnbWFpbC5jb20iLCJlbWFpbCI6ImtheWVqLnRha0BnbWFpbC5jb20iLCJwcm92aWRlcklkIjoicGFzc3dvcmQifV19LCJpYXQiOjE2Njc4NzcwODB9.ayF9GYkVlUa7kD5FP4NrkoPiw3Im-p7VJ9BicJgOrYt83TZ1GFxGmBgBEVQFOgnl-Gsk9brMmQAWkrrgshrAac3J87aBusD5st--D4aTr20ql1bq_E5drbwadhuB6G_kWkjh62akZcMgSfNJ9cU9M8shiLSgFSeui1QSUjWVl0SDFojPGvlNKrTeIOmXGRHN58pKqdRCD7f-uI27Dzy3nDk1LpU5swAAnNQUpeuokcj7SoIaH_uq1N-w15hJ6-fe0wmd9WSFoBUO2irHiv1AizInIk2sryQOfjSRrYD-U0qaANFcKj_efyb_oBWKvCN4DvLm821RLQQCH21h7D8Gp68_SpKm989GoUioTa6oiUgcZMnPnwUBRv0l9IUz0bGvjH2q-RlHbysZwDaB_Iibs7kcbpxrAH5rWJRaYazlSjdrjqxcXxLpBlE6EBuIaW8cUDJbj_fKtCfzYGzV6tfjSHeTflW8wN9XZRrve66bXeZPF1sRvpjUG-qejwYYryPmGsmXEqjM9lUYDllOYmUkPrTPQ7fJE-GmtwFyMww8U3RyZvdiNk4NO7e4sCHbkM_ldhDV_SRmZrrAOnl3qX3TvdUbvTCvDZtiyomi4_AqMt9knN2uZEsJ8JFmieUQQ4n0nGjjkF_jzdAQ0coiOEKoAc2KG4qA13xi4ERkO71Rl8k

{"phoneNumber":"+14049060803","verificationCode":"492275"}
Response

HTTP/1.1 500 Internal Server Error
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 28
etag: W/"1c-GTLvyKxlvOrEj2GGBdfOAn6LHp0"
date: Tue 08 Nov 2022 03:11:22 GMT
connection: close

{"message":"Incorrect code"}

Checks

Status

  ✕ 500 (expected 200)

⚠︎ users_tests › Get User in OnBoarding

Step was skipped because previous one failed
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by dstrickland67** [comment]
The log is from my real test, the test above is from the playground.  Same behavior.  Similar results.

**Comment by mishushakov** [comment]
Thanks for the report! I noticed when I add `config.continueOnFail` to both workflow and the test it seems to work
I'll fix the bug it the upcoming release

**Comment by dstrickland67** [comment]
How did you specify it?  Also, I would not mind being a contributor.

` 
version: "1.1"
name: Status Check
env:
  host: example.com
config:
  continueOnFail: true
tests:
  example:
  steps:
  - name: GET request
    http:
    url: https://{{env.host}}1
    method: GET
    check:
      status: /^20/
  - name: GET request
    http:
    url: https://{{env.host}}
    method: GET
  check:
   status: /^20/

`

**Comment by mishushakov** [comment]
Please take a look:

```yaml
version: "1.1"
name: Status Check
env:
  host: example.com
config:
  continueOnFail: true
tests:
  example:
    config:
      continueOnFail: true
    steps:
      - name: GET request
        http:
          url: https://{{env.host}}
          method: GET
          check:
            status: 300
      - name: GET request
        http:
          url: https://{{env.host}}
          method: GET
          check:
            status: /^20/
```

**Comment by mishushakov** [comment]
If you're looking to contribute, you may take a look at your previous bug report, #57 
The issue seems to be in our [liquidless](https://github.com/stepci/liquidless) library, try to find out what happens!

Let me know if you need any help with your bug search :)

**Comment by mishushakov** [comment]
Fixed in 2.5.0

**Comment by muffl0n** [comment]
This does not seem to work (anymore?):
test.yml
```
version: "1.1"
name: Example
env:
  host: www.example.com
config:
  continueOnFail: true
tests:
  example:
    steps:
      - name: fail
        http:
          url: https://${{env.host}}/foo
          method: GET
          check:
            status: 200
      - name: 200
        http:
          url: https://${{env.host}}
          method: GET
          check:
            status: 200
```

```
$ npm exec stepci run test.yml
...
Status

  ✕ 404 (expected 200)

⚠︎ example › 200

Step was skipped because previous one failed
```
Running stepci from branch main, cause of proxy support I had to patch, see https://github.com/stepci/stepci/pull/126
But I'm also getting the same behavior in Gitlab CI running version 2.6.4 that does not use a proxy.
