### ISSUE TITLE
Allow loading tests from other directories

### ISSUE THREAD

**Issue by mishushakov** [stepci/stepci#63]
**workflow.yml**

```yaml
version: "1.1"
name: Status Check
env:
  host: example.com
testsFrom:
  - test.yml
```

**test.yml**

```yaml
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://{{env.host}}
          method: GET
          check:
            status: /^20/
```
