### ISSUE TITLE
[Bug]: UnhandledPromiseRejection in posthog-node 2.2.1

### ISSUE THREAD

**Issue by koki-develop** [stepci/stepci#74]
### What happened?

When I run the test using the `stepci` CLI, the test itself succeeds, but then I get an error `UnhandledPromiseRejection`.

```
$ stepci run ./workflow.yml
 PASS  example

Tests: 0 failed, 1 passed, 1 total
Steps: 0 failed, 1 passed, 1 total
Time:  0.109s, estimated 0s

Workflow passed after 0.109s
Give us your feedback on https://step.ci/feedback
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "CanceledError: canceled".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

`workflow.yml`:

```yaml
version: "1.1"
name: Validating JSON

config:
  http:
    baseURL: https://jsonplaceholder.typicode.com

env:
  postId: "2"

tests:
  example:
    steps:
      - name: GET request
        http:
          url: /posts/${{env.postId}}
          method: GET
          check:
            status: 200
            jsonpath:
              $.id: ${{env.postId}}
              $.userId: 1
```

---

The same error occurs when using [github actions](https://github.com/marketplace/actions/step-ci-action).
logs: https://github.com/koki-develop/stepci-example/actions/runs/3551276044/jobs/5965323631
`.github/workflows/main.yml`:

```yaml
name: api test

on:
  push:

jobs:
  with-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stepci/stepci@main
        with:
          workflow: workflow.yml
```

---

This error does not occur when using `@stepci/runner`, so there may be some problem with `stepci` cli.
The workflow below uses `@stepci/runner` in `vitest`, but no error occurs.

logs: https://github.com/koki-develop/stepci-example/actions/runs/3551276044/jobs/5965323586

### What did you expect to happen?

After the test is completed, it ends without error as it is.

### Version

2.5.1

### Environment

Node v16.18.1

### How can we reproduce this bug?

commands:

```
$ git clone git@github.com:koki-develop/stepci-example.git
$ cd stepci-example
$ stepci run ./workflow.yml
```

output:

```
 PASS  example

Tests: 0 failed, 1 passed, 1 total
Steps: 0 failed, 1 passed, 1 total
Time:  0.132s, estimated 0s

Workflow passed after 0.132s
Give us your feedback on https://step.ci/feedback
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "CanceledError: canceled".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

exit code:

```
$ echo $?
1
```

### Relevant log output

```shell
PASS  example

Tests: 0 failed, 1 passed, 1 total
Steps: 0 failed, 1 passed, 1 total
Time:  0.132s, estimated 0s

Workflow passed after 0.132s
Give us your feedback on https://step.ci/feedback
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "CanceledError: canceled".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

### Would you be interested in working on a bugfix for this issue?

- [x] Yes! Assign me
