### ISSUE TITLE
trpc nested router 

### ISSUE THREAD

**Issue by 7flash** [stepci/stepci#81]
I have created a new router for testing paths, then trying to invoke from workflow, following fails with error "no query procedure on path", - what's the correct way to specify path here?

```
version: "1.1"
name: tRPC
env:
  host: http://localhost:8000/trpc
tests:
  first:
    steps:
      - name: Second
        http:
          url: ${{env.host}}
          trpc:
            query:
                test/second: Value
          check:
            status: /^20/
```

test/second - seems to be wrong way to invoke nested router, what's the right way?
