### ISSUE TITLE
Make env and components reusable

### ISSUE THREAD

**Issue by smaktacular** [stepci/stepci#82]
env and components need to be repeated in every workflow atm.

It would be nice if we could just include them like this:

worklflow.yml:
```yaml
version: "1.1"
...
include: 
  -env.yml
  -components.yml
```

env.yml:
```yaml
env:
  var1: val1
  var2: val2
```

components.yml:
```yaml
components:
  credentials:
    example:
      username: hello
      password: world
```
