### ISSUE TITLE
[Bug]: Templating does not work for components

### ISSUE THREAD

**Issue by smaktacular** [stepci/stepci#84]
### What happened?

I tried to run a workflow using 

```bash
stepci run workflow.yml -s pat=abc
```

```yaml
components:
  credentials:
    token:
      bearer:
        token: ${{secrets.pat}}
```

token value was ${{secrets.pat}}

Tested also with env (-e) and secret instead of secrets. No luck. 

### What did you expect to happen?

token value should be abc

### Version

2.6.0

### Environment

Node 16.14.2

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
