### ISSUE TITLE
[Feature]: Set a "global" timeout for the entire workflow

### ISSUE THREAD

**Issue by AndrewFarley** [stepci/stepci#95]
### What happened?

I'd like to be able to set a job-level timeout for the entire job, not just per-step.  This is vital for being able to use StepCI in a type of regular usage scheduled on a cron without having it "overlap" the next run.

### What did you expect to happen?

If I could have a configuration such as...

```yaml
version: "1.1"
name: Sample Workflow
tests:
  example:
    timeout: 20000  # Max of 20 seconds for the entire job
    steps:
      - name: Step 1 - Example Basic Auth with headers, and retries
         http:
           timeout: 10000
           retries: 1
           url: https://google.com/BasicAuth
           method: GET
           auth:
             basic:
               username: hello
               password: world
           check:
             status: "/^20/"
      - name: Step 2 - Example with params
         http:
           timeout: 10000
           url: https://google.com/QueryParams
           method: GET
           params:
             hello: world
             world: hello
          check:
            status: "/^20/"
      - name: Step 3 - CSS Selector
         http:
           timeout: 10000
           url: https://google.com/QueryParams
           method: GET
           check:
             selectors:
               title: Google
```

With this above configuration, your run would never take longer than 20 seconds, even though you have enough timeouts in the 3 steps present which COULD take it to 30 seconds.  But because of the global timeout, if all the different steps timeout and take their max time, by the end of the second one the job will exit out (having had 20 seconds go by) and it would never execute the third one.

### Version

HEAD/Latest as of Jan 15, 2023

### Environment

node: ~18.x

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me
