### ISSUE TITLE
[Bug]: json check: expected.map is not a function

### ISSUE THREAD

**Issue by mmahut** [stepci/stepci#98]
### What happened?

Simple JSON check fails with `expected.map is not a function`.

```
$ stepci run ./workflow.yml 
 FAIL  example

Summary

  ✕ GET request failed after 0.334s

⚠︎ example › GET request

expected.map is not a function


Tests: 1 failed, 0 passed, 1 total
Steps: 1 failed, 0 skipped, 0 passed, 1 total
Time:  0.401s, estimated 0s
CO2:   0.00001g

Workflow failed after 0.401s
Give us your feedback on https://step.ci/feedback
```

### What did you expect to happen?

The check to pass.

### Version

2.6.2

### Environment

v16.16.0

### How can we reproduce this bug?

Try to run.

```version: "1.1"
name: Status Check
env:
  host: cardano-mainnet.blockfrost.io
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://${{env.host}}/api/v0/health
          method: GET
          check:
            json:
              is_healthy: true
```

The output:

```
$ curl -s https://cardano-mainnet.blockfrost.io/api/v0/health | jq
{
  "is_healthy": true
}
```

### Relevant log output

```shell
expected.map is not a function
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
I could reproduce the bug. For now, you can use JSONPath expressions to verify JSON response

```yaml
name: Status Check
env:
  host: cardano-mainnet.blockfrost.io
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://${{env.host}}/api/v0/health
          method: GET
          check:
            jsonpath:
              $.is_healthy: true
```
